image: 8base/docker-amazonlinux-node

test:
  environment: testing
  script:  
    - NODE_ENV=testing npm install
    - npm run tslint
  tags:
    - docker
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

publish:  
  stage: deploy
  environment: production
  only:
    - tags
  script:
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish --access public
  tags:
    - docker    

cache:
  key: "$CI_PROJECT_PATH_SLUG"
  paths:
  - node_modules
